runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_HOST: "localhost"
  DB_USER: "bookadmin"
  DB_PASS: "bookadmin"
  DB_NAME: "bookstore"
  INSTANCE_CONNECTION_NAME: "sonic-arcadia-444512-n2:asia-south1:bookstore-db"

beta_settings:
  cloud_sql_instances: "sonic-arcadia-444512-n2:asia-south1:bookstore-db"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto